### ISSUE TITLE
OSPy language TODO

### ISSUE THREAD

**Issue by martinpihrt** [martinpihrt/OSPy#11]
- [ ] before sending the mistakes I read page: <https://pihrt.com/elektronika/248-moje-rapsberry-pi-zavlazovani-zahrady>
- [ ] is a hardware problem with www.pihrt.com printed board
- [ x] is a software OSPy <https://github.com/martinpihrt/OSPy> problem
- [ ] is a plugin <https://github.com/martinpihrt/OSPy-plugins> problem

**Comment by martinpihrt** [comment]
Fixed
