### ISSUE TITLE
Sensor TODO

### ISSUE THREAD

**Issue by martinpihrt** [martinpihrt/OSPy#12]
- [ ] before sending the mistakes I read page: <https://pihrt.com/elektronika/248-moje-rapsberry-pi-zavlazovani-zahrady>
- [ ] is a hardware problem with www.pihrt.com printed board
- [ ] is a software OSPy <https://github.com/martinpihrt/OSPy> problem
- [x ] is a plugin <https://github.com/martinpihrt/OSPy-plugins> problem

In the ESP32 sensors, log the value of the source and WIFI signal into the table and graph.

**Comment by martinpihrt** [comment]
is done
